from bs4 import BeautifulSoup
grouplist = open('grouplist.txt').read().split('\n')
checklist = '''<div><div class="UserRow__userRow___1qIxl UserRow__clickable___1mA1P"><div class="UserRow__avatarContainer___2c7ao"><div class="UserRow__avatar___11axX"><div class="avatar"><div class="avatar__content" data-text="A"></div></div></div></div><div class="UserRow__info___2njNu"><div class="UserRow__nameContainer___1jXod"><div class="UserRow__name___3wiGF">Aleksey Smagin</div></div></div></div><div class="UserRow__userRow___1qIxl UserRow__clickable___1mA1P"><div class="UserRow__avatarContainer___2c7ao"><div class="UserRow__avatar___11axX"><div class="avatar"><div class="avatar__content" data-text="AS"></div></div></div></div><div class="UserRow__info___2njNu"><div class="UserRow__nameContainer___1jXod"><div class="UserRow__name___3wiGF">Aleksey <span>Smagin</span></div></div></div></div><div class="UserRow__userRow___1qIxl UserRow__clickable___1mA1P"><div class="UserRow__avatarContainer___2c7ao"><div class="UserRow__avatar___11axX"><div class="avatar"><div class="avatar__content" data-text="A"></div></div></div></div><div class="UserRow__info___2njNu"><div class="UserRow__nameContainer___1jXod"><div class="UserRow__name___3wiGF">Alina Gusynina</div></div></div></div><div class="UserRow__userRow___1qIxl UserRow__clickable___1mA1P"><div class="UserRow__avatarContainer___2c7ao"><div class="UserRow__avatar___11axX"><div class="avatar"><div class="avatar__content" data-text="AS"></div></div></div></div><div class="UserRow__info___2njNu"><div class="UserRow__nameContainer___1jXod"><div class="UserRow__name___3wiGF">Andrew <span>Scott</span></div></div></div></div><div class="UserRow__userRow___1qIxl UserRow__clickable___1mA1P"><div class="UserRow__avatarContainer___2c7ao"><div class="UserRow__avatar___11axX"><div class="avatar"><div class="avatar__content" data-text="AК"></div></div></div></div><div class="UserRow__info___2njNu"><div class="UserRow__nameContainer___1jXod"><div class="UserRow__name___3wiGF">Aлиса <span>Крутских</span></div></div></div></div><div class="UserRow__userRow___1qIxl UserRow__clickable___1mA1P"><div class="UserRow__avatarContainer___2c7ao"><div class="UserRow__avatar___11axX"><div class="avatar"><div class="avatar__content" data-text="EP"></div></div></div></div><div class="UserRow__info___2njNu"><div class="UserRow__nameContainer___1jXod"><div class="UserRow__name___3wiGF">Ekaterina <span>Paramonova</span></div></div></div></div><div class="UserRow__userRow___1qIxl UserRow__clickable___1mA1P"><div class="UserRow__avatarContainer___2c7ao"><div class="UserRow__avatar___11axX"><div class="avatar"><div class="avatar__content" data-text="EV"></div></div></div></div><div class="UserRow__info___2njNu"><div class="UserRow__nameContainer___1jXod"><div class="UserRow__name___3wiGF">Ekaterina <span>Vlasova</span></div></div></div></div></div>'''
for name in grouplist:
    if name in checklist:
        print(name)

checklist = BeautifulSoup(checklist)
checklist = BeautifulSoup.prettify(checklist)
print(checklist)
